; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c6-devkitc-1]
platform = espressif32
board = esp32-c6-devkitc-1
framework = espidf

monitor_speed = 115200
monitor_raw = yes

upload_protocol = esptool

debug_tool = custom
debug_server = 
    C:\Users\liste\.espressif\tools\openocd-esp32\v0.12.0-esp32-20250707\openocd-esp32\bin\openocd.exe
    -s C:\Users\liste\.espressif\tools\openocd-esp32\v0.12.0-esp32-20250707\openocd-esp32\share\openocd\scripts
    -f board\esp32c6-builtin.cfg
    -c "adapter speed 5000"

build_type = debug
build_flags = -Og -g3
debug_load_mode = manual
debug_load_cmds = load$
