idf_component_register(
    SRCS 
        "main.c"
        "button/button_handler.c"
        "ir/ir_handler.c"
        "lcd/lcd_assets.c"
        "lcd/st7789.c"
        "led/rgb_led.c"
        "lvgl/lvgl_display.c"
        "lvgl/lvgl_ui.c"
        "pot/pot_adc.c"
        "utils/app_config.c"
    INCLUDE_DIRS 
        "."
        "app"
        "button"
        "ir"
        "lcd"
        "lcd/assets"
        "led"
        "lvgl"
        "pot"
        "utils"
)