idf_component_register(
    SRCS 
        "main.c"
        "button/button_handler.c"
        "buzzer/buzzer.c"
        "ir/ir_handler.c"
        "lcd/lcd_assets.c"
        "lcd/st7789.c"
        "led/rgb_led.c"
        "lvgl/lvgl_display.c"
        "pot/pot_adc.c"
        "utils/app_config.c"
        "app/event_bus/event_bus.c"
        "app/state/app_state.c"
        "app/input/input_manager.c"
        "app/input/pot_monitor.c"
        "app/ui/ui_controller.c"
        "app/ui/screens/screen.c"
        "app/ui/screens/screen_manager.c"
        "app/ui/screens/main_screen.c"
    INCLUDE_DIRS 
        "."
        "app"
        "app/event_bus"
        "app/state"
        "app/actions"
        "app/input"
        "app/ui"
        "app/ui/screens"
        "button"
        "buzzer"
        "buzzer/assets"
        "ir"
        "lcd"
        "lcd/assets"
        "led"
        "lvgl"
        "pot"
        "utils"
)
